/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.VistasAdmin;

/**
 *
 * @author maria
 */
public class gestionActividades extends javax.swing.JFrame {

    /**
     * Creates new form gestionActividades
     */
    public gestionActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblNuevaActividad = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnMenu = new java.awt.Button();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblAsignarActividad = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblSeleccionarCuadrilla = new javax.swing.JLabel();
        txtSeleccionarCuadrilla = new javax.swing.JComboBox<>();
        lblSeleccionarColonia2 = new javax.swing.JLabel();
        txtSeleccionarColonia = new javax.swing.JComboBox<>();
        btnGuardarAsignacion = new java.awt.Button();
        btnVerAsignaciones = new java.awt.Button();
        lblVerAsignaciones1 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblIdActividad = new javax.swing.JLabel();
        txtIdActividad = new javax.swing.JTextField();
        lblicono1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblGuardarAsignacion1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNuevaActividad.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNuevaActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarea.png"))); // NOI18N
        lblNuevaActividad.setText("CREAR NUEVA ACTIVIDAD");
        lblNuevaActividad.setName("lblCuadernito"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblNuevaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblNuevaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 80));

        lblFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblFecha.setText("FECHA AGENDADA");
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setName("txtDescripcion"); // NOI18N
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 290, 100));

        btnMenu.setActionCommand("MENU");
        btnMenu.setBackground(new java.awt.Color(255, 153, 153));
        btnMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenu.setLabel("MENU");
        btnMenu.setName("btnMenu"); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 100, 40));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAsignarActividad.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblAsignarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asignar.png"))); // NOI18N
        lblAsignarActividad.setText("ASIGNAR ACTIVIDAD");
        lblAsignarActividad.setName("lblEquipoManita"); // NOI18N
        jPanel8.add(lblAsignarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 310, 80));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 80));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        lblSeleccionarCuadrilla.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSeleccionarCuadrilla.setText("SELECCIONAR CUADRILLA");
        jPanel6.add(lblSeleccionarCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        txtSeleccionarCuadrilla.setName("cbSeleccionarCuadrilla"); // NOI18N
        txtSeleccionarCuadrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeleccionarCuadrillaActionPerformed(evt);
            }
        });
        jPanel6.add(txtSeleccionarCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 340, -1));

        lblSeleccionarColonia2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSeleccionarColonia2.setText("SELECCIONAR COLONIA");
        jPanel6.add(lblSeleccionarColonia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        txtSeleccionarColonia.setName("cbSeleccionarColonia"); // NOI18N
        jPanel6.add(txtSeleccionarColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 340, -1));

        btnGuardarAsignacion.setActionCommand("MENU");
        btnGuardarAsignacion.setBackground(new java.awt.Color(255, 255, 102));
        btnGuardarAsignacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardarAsignacion.setLabel("GUARDAR ASIGNACION");
        btnGuardarAsignacion.setName("btnGuardarAsignacion"); // NOI18N
        btnGuardarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsignacionActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardarAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 190, 30));

        btnVerAsignaciones.setBackground(new java.awt.Color(255, 153, 0));
        btnVerAsignaciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVerAsignaciones.setLabel("VER ASIGNACIONES");
        btnVerAsignaciones.setName("btnVerAsignaciones"); // NOI18N
        btnVerAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAsignacionesActionPerformed(evt);
            }
        });
        jPanel6.add(btnVerAsignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 170, 40));

        lblVerAsignaciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        lblVerAsignaciones1.setName("lblCarrito"); // NOI18N
        jPanel6.add(lblVerAsignaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 40, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 470, 700));

        lblDescripcion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDescripcion.setText("DESCRIPCIÓN");
        jPanel2.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        lblIdActividad.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblIdActividad.setText("ID ACTIVIDAD");
        jPanel2.add(lblIdActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtIdActividad.setName("txtIdActividad"); // NOI18N
        jPanel2.add(txtIdActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 60, -1));

        lblicono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        lblicono1.setName("lblCarrito"); // NOI18N
        jPanel2.add(lblicono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 40, 40));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        lblGuardarAsignacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disco-flexible.png"))); // NOI18N
        lblGuardarAsignacion1.setName("lblCarrito"); // NOI18N
        jPanel2.add(lblGuardarAsignacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 70, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnVerAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerAsignacionesActionPerformed

    private void btnGuardarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsignacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAsignacionActionPerformed

    private void txtSeleccionarCuadrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeleccionarCuadrillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeleccionarCuadrillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionActividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnGuardarAsignacion;
    private java.awt.Button btnMenu;
    private java.awt.Button btnVerAsignaciones;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsignarActividad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGuardarAsignacion1;
    private javax.swing.JLabel lblIdActividad;
    private javax.swing.JLabel lblNuevaActividad;
    private javax.swing.JLabel lblSeleccionarColonia2;
    private javax.swing.JLabel lblSeleccionarCuadrilla;
    private javax.swing.JLabel lblVerAsignaciones1;
    private javax.swing.JLabel lblicono1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtIdActividad;
    private javax.swing.JComboBox<String> txtSeleccionarColonia;
    private javax.swing.JComboBox<String> txtSeleccionarCuadrilla;
    // End of variables declaration//GEN-END:variables
}
