/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.VistasAdmin;

/**
 *
 * @author maria
 */
public class gestionUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form gestionUusarios
     */
    public gestionUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblGestionUsuarios = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblConfirme = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblAPaterno = new javax.swing.JLabel();
        lblAMaterno = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtConfirmeContrasena = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtAPaterno = new javax.swing.JTextField();
        txtAMaterno = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnVerUsuarios = new java.awt.Button();
        btnMenu = new java.awt.Button();
        lblPuntoRojo = new javax.swing.JLabel();
        lblGestion2 = new javax.swing.JLabel();
        lblVerUsuarios = new javax.swing.JLabel();
        lblMenu2 = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        btnConsultar = new java.awt.Button();
        btnGuardar = new java.awt.Button();
        btnDelete = new java.awt.Button();
        lblfondo = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        btnActualizar1 = new java.awt.Button();
        lblGuardar1 = new javax.swing.JLabel();
        lblConsultar1 = new javax.swing.JLabel();
        lblActualizar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(222, 211, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestionUsuarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGestionUsuarios.setText("GESTIÓN DE USUARIOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblGestionUsuarios)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGestionUsuarios)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 290, 50));

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setBackground(new java.awt.Color(204, 204, 204));
        lblNombre.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblNombre.setText("NOMBRE:");
        jPanel3.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblConfirme.setBackground(new java.awt.Color(204, 204, 204));
        lblConfirme.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblConfirme.setText("CONFIRME  CONTRASEÑA");
        jPanel3.add(lblConfirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 20));

        lblId.setBackground(new java.awt.Color(204, 204, 204));
        lblId.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblId.setText("DEFINA UN ID:");
        lblId.setName("lblId"); // NOI18N
        jPanel3.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblAPaterno.setBackground(new java.awt.Color(204, 204, 204));
        lblAPaterno.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblAPaterno.setText("APELLIDO PATERNO:");
        jPanel3.add(lblAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblAMaterno.setBackground(new java.awt.Color(204, 204, 204));
        lblAMaterno.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblAMaterno.setText("APELLIDO MATERNO:");
        jPanel3.add(lblAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblCorreo.setBackground(new java.awt.Color(204, 204, 204));
        lblCorreo.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblCorreo.setText("CORREO:");
        jPanel3.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtConfirmeContrasena.setName("txtConfirmeContrasena"); // NOI18N
        jPanel3.add(txtConfirmeContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 180, -1));

        txtId.setName("txtId"); // NOI18N
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, -1));

        txtNombre.setName("txtNombre"); // NOI18N
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 220, -1));

        txtAPaterno.setName("txtApellidoPaterno"); // NOI18N
        jPanel3.add(txtAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, -1));

        txtAMaterno.setName("txtApellidoMaterno"); // NOI18N
        jPanel3.add(txtAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, -1));

        txtCorreo.setName("txtCorreo"); // NOI18N
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, -1));

        lblpassword.setBackground(new java.awt.Color(204, 204, 204));
        lblpassword.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblpassword.setText("CONTRASEÑA");
        jPanel3.add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtContrasena.setName("txtContrasena"); // NOI18N
        jPanel3.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 180, -1));

        lblUsuario.setBackground(new java.awt.Color(204, 204, 204));
        lblUsuario.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblUsuario.setText("USUARIO");
        jPanel3.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtUsuario.setName("txtUsuario"); // NOI18N
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 220, -1));

        lblTelefono.setBackground(new java.awt.Color(204, 204, 204));
        lblTelefono.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblTelefono.setText("TELEFONO:");
        jPanel3.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtTelefono.setName("txtTelefono"); // NOI18N
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 220, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 410, 340));

        btnVerUsuarios.setBackground(new java.awt.Color(255, 153, 51));
        btnVerUsuarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVerUsuarios.setLabel("VER USUARIOS");
        btnVerUsuarios.setName("btnVerUsuarios"); // NOI18N
        btnVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 160, 50));

        btnMenu.setActionCommand("MENU");
        btnMenu.setBackground(new java.awt.Color(255, 153, 153));
        btnMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenu.setLabel("MENU");
        btnMenu.setName("btnMenu"); // NOI18N
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 100, 50));

        lblPuntoRojo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblPuntoRojo.setForeground(new java.awt.Color(0, 153, 153));
        lblPuntoRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/punto.png"))); // NOI18N
        lblPuntoRojo.setText("Clean Colony Manager");
        lblPuntoRojo.setMaximumSize(new java.awt.Dimension(723, 512));
        lblPuntoRojo.setName("lblPuntoRojo"); // NOI18N
        jPanel1.add(lblPuntoRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblGestion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir-usuario.png"))); // NOI18N
        lblGestion2.setName("lblManos"); // NOI18N
        jPanel1.add(lblGestion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 140));

        lblVerUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        lblVerUsuarios.setName("lblCarrito"); // NOI18N
        jPanel1.add(lblVerUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 40, 40));

        lblMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        lblMenu2.setName("lblCarrito"); // NOI18N
        jPanel1.add(lblMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 40, 40));

        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe Cuadrilla", "Trabajador" }));
        jPanel1.add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 480, 700));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultar.setActionCommand("ACTUALIZAR");
        btnConsultar.setBackground(new java.awt.Color(102, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConsultar.setLabel("CONSULTAR");
        btnConsultar.setName("btnConsultar"); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel6.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, 30));

        btnGuardar.setBackground(new java.awt.Color(102, 255, 102));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGuardar.setLabel("GUARDAR");
        btnGuardar.setName("btnGuardar"); // NOI18N
        jPanel6.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 140, 30));

        btnDelete.setActionCommand("ACTUALIZAR");
        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDelete.setLabel("ELIMINAR");
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel6.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 140, 30));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpieza.png"))); // NOI18N
        lblfondo.setName("lblTina"); // NOI18N
        jPanel6.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 146, 156));

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-eliminar.png"))); // NOI18N
        lblEliminar.setName("lblCarrito"); // NOI18N
        jPanel6.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 70, 70));

        btnActualizar1.setActionCommand("ACTUALIZAR");
        btnActualizar1.setBackground(new java.awt.Color(255, 255, 51));
        btnActualizar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnActualizar1.setLabel("ACTUALIZAR");
        btnActualizar1.setName("btnActualizar"); // NOI18N
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, 30));

        lblGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disco-flexible.png"))); // NOI18N
        lblGuardar1.setName("lblCarrito"); // NOI18N
        jPanel6.add(lblGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 70));

        lblConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-de-datos.png"))); // NOI18N
        lblConsultar1.setName("lblCarrito"); // NOI18N
        jPanel6.add(lblConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, 70));

        lblActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        lblActualizar1.setName("lblCarrito"); // NOI18N
        jPanel6.add(lblActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 70, 70));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 140, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnActualizar1;
    private java.awt.Button btnConsultar;
    private java.awt.Button btnDelete;
    private java.awt.Button btnGuardar;
    private java.awt.Button btnMenu;
    private java.awt.Button btnVerUsuarios;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAMaterno;
    private javax.swing.JLabel lblAPaterno;
    private javax.swing.JLabel lblActualizar1;
    private javax.swing.JLabel lblConfirme;
    private javax.swing.JLabel lblConsultar1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblGestion2;
    private javax.swing.JLabel lblGestionUsuarios;
    private javax.swing.JLabel lblGuardar1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMenu2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntoRojo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVerUsuarios;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtConfirmeContrasena;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
